### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by duilio82** [audit4j/audit4j-db#6]
database: Oracle
audit4j-db version: 2.4.1

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at org.audit4j.handler.db.AuditLogDaoImpl.createTableIfNotExists(AuditLogDaoImpl.java:112)

String values[] = tableName.split("\."); // tableName = "audit"
query.append("select count(*) from all_tables where table_name = upper('")
                        .append(values[1]).append("') and tablespace_name = upper('")
                        .append(values[0]).append("')");

audit4j.conf.yml
!Configuration
handlers: 
- !org.audit4j.handler.db.DatabaseAuditHandler
  embedded: false
  db_connection_type: jndi
  db_jndi_datasource: myJndiDS
- !org.audit4j.core.handler.ConsoleAuditHandler {}
  layout: !org.audit4j.core.layout.SimpleLayout {}

**Comment by SMART2016** [comment]
The Issue seems majorly due the implementation where its expects that the table name will be prepended with the Tablespace but its not. Ideally the framewrok should pass the table name in that manner if thats what is expected. Plus i can see that the code is using ALL_TABLES which is incorrect and should use USER_TABLES. The logic to create New audit table seems faulty too.

**Comment by janithb** [comment]
This will be fixed in #12
